services:
  cassandra:
    image: cassandra:5.0
    hostname: cassandra-local
    container_name: cassandra
    environment:
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
      CASSANDRA_DC: "dc1"
      CASSANDRA_NUM_TOKENS: "1"
      CASSANDRA_START_RPC: "false"
      JVM_EXTRA_OPTS: -Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.load_ring_state=false -Dcassandra.initial_token=1 -Dcassandra.num_tokens=nil -Dcassandra.allocate_tokens_for_local_replication_factor=nil
    ports:
      - "9042:9042"
