addSbtPlugin("com.github.sbt"   % "sbt-github-actions" % "0.25.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"        % "0.6.4")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"       % "2.5.5")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"       % "0.14.3")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release"     % "1.11.1")
